# -*- coding: utf-8 -*-
"""YOLO11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U7q3mqcF52VRcJML0Opmw_tUQpp7-heh
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive/UnderWater.v3i.yolov8.zip

!unzip /content/drive/MyDrive/UnderWater.v3i.yolov8.zip -d /content/drive/MyDrive/datasets/

!pip install ultralytics

!yolo task=detect \
mode=train \
model=yolov8s.pt \
data=/content/drive/MyDrive/datasets/data.yaml \
epochs=60 \
imgsz=100

!cp runs/detect/train2/weights/best.pt /content/drive/MyDrive/datasets/Trained_Model_yolo11.pt

!yolo task=detect \
mode=predict \
model=/content/drive/MyDrive/datasets/Trained_Model_yolo11.pt \
conf=0.25 \
source=/content/drive/MyDrive/datasets/test/images

!yolo predict model=/content/drive/MyDrive/datasets/Trained_Model_yolo11.pt source='/content/drive/MyDrive/images (1).jpg'

!yolo predict model=/content/drive/MyDrive/datasets/Trained_Model_yolo11.pt source='/content/drive/MyDrive/images.jpg'

!yolo predict model=/content/drive/MyDrive/datasets/Trained_Model_yolo11.pt source='/content/drive/MyDrive/images (2).jpg'

!yolo predict model=/content/drive/MyDrive/datasets/Trained_Model_yolo11.pt source='/content/drive/MyDrive/images (3).jpg'

!yolo predict model=/content/drive/MyDrive/datasets/Trained_Model_yolo11.pt source='/content/drive/MyDrive/download.jpg'

!yolo predict model=/content/drive/MyDrive/datasets/Trained_Model_yolo11.pt source='/content/drive/MyDrive/template-thumbnailsite-12-800x0-c-default.png'

